export const SONG_SET_PLAYLIST_REQUEST = 'SONG_SET_PLAYLIST_REQUEST'; 
export const SONG_SET_PLAYLIST_SUCCESS = 'SONG_SET_PLAYLIST_SUCCESS';
export const SONG_SET_PLAYLIST_FAIL = 'SONG_SET_PLAYLIST_FAIL';

export const SONG_GET_PLAYLIST_REQUEST = 'SONG_GET_PLAYLIST_REQUEST'; 
export const SONG_GET_PLAYLIST_SUCCESS = 'SONG_GET_PLAYLIST_SUCCESS';
export const SONG_GET_PLAYLIST_FAIL = 'SONG_GET_PLAYLIST_FAIL';

export const SONG_SET_FAVOURITES_REQUEST = 'SONG_SET_FAVOURITES_REQUEST'; 
export const SONG_SET_FAVOURITES_SUCCESS = 'SONG_SET_FAVOURITES_SUCCESS';
export const SONG_SET_FAVOURITES_FAIL = 'SONG_SET_FAVOURITES_FAIL';

export const SONG_GET_FAVOURITES_REQUEST = 'SONG_GET_FAVOURITES_REQUEST'; 
export const SONG_GET_FAVOURITES_SUCCESS = 'SONG_GET_FAVOURITES_SUCCESS';
export const SONG_GET_FAVOURITES_FAIL = 'SONG_GET_FAVOURITES_FAIL';

export const SONG_DETAILS_REQUEST = 'SONG_LIST_REQUEST'; 
export const SONG_DETAILS_SUCCESS = 'SONG_LIST_SUCCESS';
export const SONG_DETAILS_FAIL = 'SONG_LIST_FAIL';

export const SONG_LIST_REQUEST = 'SONG_LIST_REQUEST'; 
export const SONG_LIST_SUCCESS = 'SONG_LIST_SUCCESS';
export const SONG_LIST_FAIL = 'SONG_LIST_FAIL';

export const SONG_SEARCH_LIST_REQUEST = 'SONG_SEARCH_LIST_REQUEST'; 
export const SONG_SEARCH_LIST_SUCCESS = 'SONG_SEARCH_LIST_SUCCESS';
export const SONG_SEARCH_LIST_FAIL = 'SONG_SEARCH_LIST_FAIL';